---
title: "Report for the Markov model (cohort state-transition model)"
date: 2020.12.16
header-includes:
   - \usepackage{amsmath}
   - \usepackage{booktabs}
   - \usepackage{fancyhdr}
   - \pagestyle{fancy}
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(xtable)

```


# Results from the paper

These two tables are from the result part of the paper by Yaqin Si.
```{r message=FALSE}
strategy_names <- c("strategy1", "strategy2", "strategy3")
# QALY
QALY <- data.frame("est" = c(498,691,654),
                   "LB" = c(103,233,105),
                   "UB" = c(894,194,1108))
rownames(QALY) <- strategy_names
# Prevent CVD events
num_CVD <- data.frame("est" = c(298,374,346),
                   "LB" = c(155,181,154),
                   "UB" = c(441,567,538))
rownames(num_CVD) <- strategy_names
```

```{r, echo=FALSE, results='asis'}
t1 <- kable(QALY, format = "latex", booktabs = TRUE)
t2 <- kable(num_CVD, format = "latex", booktabs = TRUE)
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{Increased QALY with no screening}
      \\centering",
        t1,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{Prevent CVD events}",
        t2,
    "\\end{minipage} 
\\end{table}"
))  
```

## Markov model

```{r}
# parameters TODO 
cycle <- 4
factor <- 0.8
```


```{r}
# transition probability and related parameters
# calculated by ratetoprob function, based on the incidence of a disease and incidence of a death from the Global Burden of Disease Collaborative Network
library(readr)
rate_data <- read_csv("data/ghdx_data.csv")
source("./function/transform_func.R")
p_live_oth_death <- RateToProb(rate=rate_data$rate_death_nonCVD,t=cycle)
p_live_cvd <- RateToProb(rate=rate_data$rate_incidence_CVD,t = cycle)
p_live_cvdth <- RateToProb(rate=rate_data$rate_death_CVD,t = cycle)
# incidence rate of the cohort of 3 levels
p_live_cvd_l <- ProbFactor(p_live_cvd,factor)
p_live_cvd_m <- ProbFactor(p_live_cvd,factor)
p_live_cvd_h <- ProbFactor(p_live_cvd,factor)
# death rate of the cohort of 3 levels
p_live_cvdth_l <- ProbFactor(p_live_cvdth,factor)
p_live_cvdth_m <- ProbFactor(p_live_cvdth,factor)
p_live_cvdth_h <- ProbFactor(p_live_cvdth,factor)



```


```{r}
# Health Status
```


```{r}
# chi-squared test

# t-test

```

```{r}
HR_l_stg1	<- 0.63
HR_l_stg2	<- 0.43
HR_l_stg3	<- 0.45
HR_m_stg1	<- 1.56
HR_m_stg2	<- 0.97
HR_m_stg3	<- 1.09
HR_h_stg1	<- 1.6
HR_h_stg2	<- 2.06
HR_h_stg3	<- 2.11
```

