---
title: "left"
output: pdf_document
---


# Strategy 2
```{r}
p_live_cvd_l <- ProbFactor(p_live_cvd,HR_l_stg2)
p_live_cvd_m <- ProbFactor(p_live_cvd,HR_m_stg2*
                             HR_smk_cvd*HR_salt_cvd*HR_wtc_cvd)  # lifestyle intervention
p_live_cvd_h <- ProbFactor(p_live_cvd,HR_h_stg2*
                             HR_smk_cvdth*HR_salt_cvdth*HR_wtc_dth*    # lifestyle intervention
                             HR_hpt_lip_cvdth)   # treatment intervention 

# transition probability to death
p_live_cvdth_l <- ProbFactor(p_live_cvdth,1)    # equal
p_live_cvdth_m <- ProbFactor(p_live_cvdth,1*
                               HR_smk_cvd*HR_salt_cvd*HR_wtc_cvd)  # lifestyle intervention 
p_live_cvdth_h <- ProbFactor(p_live_cvdth,1.7*
                               HR_smk_cvdth*HR_salt_cvdth*HR_wtc_dth* # lifestyle intervention
                               HR_hpt_lip_cvdth) # treatment intervention 
```

```{r}
risk_levels <- c("low","medium","high")
result_CVD_lmh <- matrix(0,  nrow = 14,ncol = 3,
                         dimnames = list(names_population, risk_levels))
p_live_cvd_lmh <- matrix(cbind(p_live_cvd_l,p_live_cvd_m,p_live_cvd_h), ncol=3,
                         dimnames = list(names_population,risk_levels))
p_live_cvdth_lmh <- matrix(cbind(p_live_cvdth_l,p_live_cvdth_m,p_live_cvdth_h), ncol=3,
                           dimnames = list(names_population,risk_levels))
patient_group <- matrix(cbind(population_data[29:42,]$low,
                              population_data[29:42,]$medium,
                              population_data[29:42,]$high),
       ncol = 3, nrow=14,dimnames = list(names_population,risk_levels))
for(r in 1:3){  # three rish groups
  for(i in 1:14){
  if(i != 7 && i != 14){
    a_P <- array(0, dim = c(n_states, n_states, 10),
               dimnames = list(v_names_states, v_names_states, 1:10))
    a_P["S1", "S1", 1:5] <- 1-(p_live_cvd_lmh[i,r]*(1-p_acvd_cvdth[i]) +
                               p_live_cvdth_lmh[i,r]*p_live_cvd_lmh[i,r]*p_acvd_cvdth[i] +
                               p_live_oth_death[i])
    a_P["S1", "S2", 1:5] <- p_live_cvd_lmh[i,r]*(1-p_acvd_cvdth[i])
    a_P["S1", "S3", 1:5] <- p_live_cvdth_lmh[i,r]*p_live_cvd_lmh[i,r]*p_acvd_cvdth[i]
    a_P["S1", "S4", 1:5] <- p_live_oth_death[i]
    a_P["S2", "S1", 1:5] <- 0
    a_P["S2", "S2", 1:5] <- 1-p_live_oth_death[i]-
      (p_ccvd_cvdth[i]+p_ccvd_acvd[i]*p_acvd_cvdth[i])
    a_P["S2", "S3", 1:5] <- p_ccvd_cvdth[i]+
      p_ccvd_acvd[i]*p_acvd_cvdth[i]
    a_P["S2", "S4", 1:5] <- p_live_oth_death[i]
    a_P["S3", "S3", 1:5] <- 1
    a_P["S4", "S4", 1:5] <- 1

    a_P["S1", "S1", 6:10] <-  1-(p_live_cvd_lmh[i+1]*(1-p_acvd_cvdth[i+1])+
                             p_live_cvdth_lmh[i+1]*p_live_cvd_lmh[i+1]*p_acvd_cvdth[i+1]
                             +p_live_oth_death[i+1])
    a_P["S1", "S2", 6:10] <- p_live_cvd_lmh[i+1]*(1-p_acvd_cvdth[i+1])
    a_P["S1", "S3", 6:10] <- p_live_cvdth_lmh[i+1]*p_live_cvd_lmh[i+1]*p_acvd_cvdth[i+1]
    a_P["S1", "S4", 6:10] <- p_live_oth_death[i+1]
    a_P["S2", "S1", 6:10] <- 0
    a_P["S2", "S2", 6:10] <- 1-p_live_oth_death[i+1]-
       (p_ccvd_cvdth[i+1]+p_ccvd_acvd[i+1]*p_acvd_cvdth[i+1])
    a_P["S2", "S3", 6:10] <- p_ccvd_cvdth[i+1]+p_ccvd_acvd[i+1]*p_acvd_cvdth[i+1]
    a_P["S2", "S4", 6:10] <-  p_live_oth_death[i+1]
    a_P["S3", "S3", 6:10] <- 1
    a_P["S4", "S4", 6:10] <- 1
  
    v_s_init <- c(state0 = 1, state1 = 0, state2 = 0, state3 = 0) 
    m_M <- matrix(0,nrow     = (n_t), ncol = n_states, 
                  dimnames = list(0:(n_t-1), v_names_states))
    m_M[1, ] <- v_s_init
    for(t in 1:9){
      m_M[t + 1, ] <- m_M[t, ] %*% a_P[, , t]
    }
    result_m_M[,,i] <- m_M
  }
    if(i == 7 | i == 14){
    a_P <- array(0, dim = c(n_states, n_states, 10),
               dimnames = list(v_names_states, v_names_states, 1:10))
    a_P["S1", "S1", 1:10] <- 1-(p_live_cvd[i]*(1-p_acvd_cvdth[i]) +
                               p_live_cvdth[i]*p_live_cvd[i]*p_acvd_cvdth[i] +
                               p_live_oth_death[i])
    a_P["S1", "S2", 1:10] <- p_live_cvd[i]*(1-p_acvd_cvdth[i])
    a_P["S1", "S3", 1:10] <- p_live_cvdth[i]*p_live_cvd[i]*p_acvd_cvdth[i]
    a_P["S1", "S4", 1:10] <- p_live_oth_death[i]
    a_P["S2", "S1", 1:10] <- 0
    a_P["S2", "S2", 1:10] <- 1-p_live_oth_death[i]-
      (p_ccvd_cvdth[i]+p_ccvd_acvd[i]*p_acvd_cvdth[i])
    a_P["S2", "S3", 1:10] <- p_ccvd_cvdth[i]+
      p_ccvd_acvd[i]*p_acvd_cvdth[i]
    a_P["S2", "S4", 1:10] <- p_live_oth_death[i]
    a_P["S3", "S3", 1:10] <- 1
    a_P["S4", "S4", 1:10] <- 1
    
    v_s_init <- c(state0 = 1, state1 = 0, state2 = 0, state3 = 0) 
    m_M <- matrix(0,nrow     = (n_t), ncol = n_states, 
                  dimnames = list(0:(n_t-1), v_names_states))
    m_M[1, ] <- v_s_init
    for(t in 1:9){
      m_M[t + 1, ] <- m_M[t, ] %*% a_P[, , t]
    }
    result_m_M[,,i] <- m_M
  }
}

prob_CVD_group2 <- matrix(0, ncol=14, nrow=10,
                     dimnames=list(paste0("t",0:9),names_population))
for (i in 1:14){
  prob_CVD_group2[,i] <- result_m_M[, 1, i]* p_live_cvd_lmh[i,r]
}
patient_group <- matrix(cbind(population_data[15:28,]$low,
                              population_data[15:28,]$medium,
                              population_data[15:28,]$high),
       ncol = 3, nrow=14,dimnames = list(names_population,risk_levels))
result_CVD <- matrix(NA)
for(j in 1:14){
  result_CVD_lmh[j,r] <- sum(prob_CVD_group2[,j]*patient_group[j,r])
} 
}
```


```{r results="asis"}
print(xtable((rbind(result_CVD_lmh, "sum" = colSums(result_CVD_lmh))),
      caption = "CVD events for patients under Strategy2"),
      caption.placement="top",comment=FALSE)
result_CVD_stg2 <- sum(result_CVD_lmh)
result_CVD_stg2
```


