---
title: "stg0_Jiamin"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}
library(knitr)
library(xtable)
library(darthtools)
library(ggplot2)
library(readr)
set.seed(1)
source("function/transform_func.R")
rate_data <- read_csv("data/ghdx_data.csv")
population_data <- read_csv("data/Normal3Stra_data.csv")
population_data <- data.frame(population_data)
```

```{r}
p_live_cvd <- rate_to_prob(rate_data$incidence,1) 
p_live_cvdth <- rate_to_prob(rate_data$death_CVD,1) 
p_live_oth_death <- rate_to_prob(rate_data$death_nonCVD,1) 

p_ccvd_cvdth <- rate_to_prob(p_live_cvdth,3.12) 
p_ccvd_acvd <- rate_to_prob(p_live_cvd,1.37)  

n_state=4
names_state=c("s1","s2","s3","s4")
n_population=14
names_population=c("m_40","m_45","m_50","m_55","m_60","m_65","m_70",
                   "f_40","f_45","f_50","f_55","f_60","f_65","f_70")

```

```{r}
a_P<-array(0, dim=c(n_state,n_state,10,n_population),
           dimnames=list(names_state,names_state,1:10,names_population))
p1<-array(0,dim=c(10,n_population),dimnames=list(1:10,names_population))  
p2<-array(0,dim=c(10,n_population),dimnames=list(1:10,names_population))  
p4<-array(0,dim=c(10,n_population),dimnames=list(1:10,names_population))  
set.seed(1)
p8<-array(runif(140,min=0.02,max=0.1),dim=c(10,n_population),dimnames=list(1:10,names_population))  
p5<-array(0,dim=c(10,n_population),dimnames=list(1:10,names_population))  
p6<-array(0,dim=c(10,n_population),dimnames=list(1:10,names_population))  

for (i in 1:14){ 
  if (i==7 | i==14){
    a_P["s1","s3",1:10,i]<- p_live_oth_death[i]
    a_P["s2","s3",1:10,i]<- p_live_oth_death[i]
    for ( j in 1:10){
      p2[j,i]<-p_live_cvdth[i]+p_live_cvd[i]*p8[j,i]
      p1[j,i]<-p_live_cvd[i]*(1-p8[j,i])
      p4[j,i]<-1-p1[j,i]-p2[j,i]-p_live_oth_death[i]
      p5[j,i]<-p_ccvd_cvdth[i]+p_ccvd_acvd[i]*p8[j,i]
      p6[j,i]<-1-p5[j,i]-p_live_oth_death[i]
      a_P["s1","s2",j,i]<-p1[j,i]
      a_P["s1","s4",j,i]<-p2[j,i]
      a_P["s1","s1",j,i]<-p4[j,i]
      a_P["s2","s2",j,i]<-p6[j,i]
      a_P["s2","s4",j,i]<-p5[j,i]
    }
    a_P["s3","s3",1:10,i]<-1
    a_P["s4","s4",1:10,i]<-1
  }
  else{
    a_P["s1","s3",1:5,i]<-p_live_oth_death[i]
    a_P["s2","s3",1:5,i]<-p_live_oth_death[i]
    for ( j in 1:5){
      p2[j,i]<-p_live_cvdth[i]+p_live_cvd[i]*p8[j,i]
      p1[j,i]<-p_live_cvd[i]*(1-p8[j,i])
      p4[j,i]<-1-p1[j,i]-p2[j,i]-p_live_oth_death[i]
      p5[j,i]<-p_ccvd_cvdth[i]+p_ccvd_acvd[i]*p8[j,i]
      p6[j,i]<-1-p5[j,i]-p_live_oth_death[i]
      a_P["s1","s2",j,i]<-p1[j,i]
      a_P["s1","s4",j,i]<-p2[j,i]
      a_P["s1","s1",j,i]<-p4[j,i]
      a_P["s2","s2",j,i]<-p6[j,i]
      a_P["s2","s4",j,i]<-p5[j,i]
    }
    a_P["s3","s3",1:5,i]<-1
    a_P["s4","s4",1:5,i]<-1
    
    a_P["s1","s3",6:10,i]<-p_live_oth_death[i+1]
    a_P["s2","s3",6:10,i]<-p_live_oth_death[i+1]
    for ( j in 6:10){
      p2[j,i]<-p_live_cvdth[i+1]+p_live_cvd[i+1]*p8[j,i]
      p1[j,i]<-p_live_cvd[i+1]*(1-p8[j,i])
      p4[j,i]<-1-p1[j,i]-p2[j,i]-p_live_oth_death[i+1]
      p5[j,i]<-p_ccvd_cvdth[i+1]+p_ccvd_acvd[i+1]*p8[j,i]
      p6[j,i]<-1-p5[j,i]-p_live_oth_death[i+1]
      a_P["s1","s2",j,i]<-p1[j,i]
      a_P["s1","s4",j,i]<-p2[j,i]
      a_P["s1","s1",j,i]<-p4[j,i]
      a_P["s2","s2",j,i]<-p6[j,i]
      a_P["s2","s4",j,i]<-p5[j,i]
    }
    a_P["s3","s3",6:10,i]<-1
    a_P["s4","s4",6:10,i]<-1
  }
}










a_P[ , ,1, 1] # m40 1st year
a_P[ , ,1, 5] # m40 5st year
a_P[ , ,1, 10] # m40 10st year
```

```{r}
population<-matrix(c(40,45,50,55,60,65,70,
                     40,45,50,55,60,65,70,
                     229,444,422,410,322,160,116,
                     498,856,822,842,519,394,187,
                    1,1,1,1,1,1,1,2,2,2,2,2,2,2),
                   ncol=3,nrow=14,
                   dimnames=list(1:14,c("age","num","sex")),byrow=F)
```

```{r}
s_start<-matrix(NA,nrow=14,ncol=4,dimnames=list(1:14,names_state))
s_start[,1]<-population[1:14,2]
s_start[,2]<-0
s_start[,3]<-0
s_start[,4]<-0
## s_start
m_M<-array(NA,dim=c(10,4,14),dimnames=list(1:10,names_state,names_population))
for (i in 1:14) {
  m_M[1,,i]<-s_start[i,]
}
## m_M
uti<-c(1,0.9,0,0)  
uti2 <- -0.038 
year<-c(1,1,0,0)
n_cnew<-array(0,dim=c(10,1,14),dimnames=list(1:10,"num",names_population))  
n_clive<-array(0,dim=c(10,1,14),dimnames=list(1:10,"num",names_population)) 
n_cvd<-0 
n_cd<-0 
n_nd<-0  
n_d<-0 
qaly<-0 
qaly_m<-array(0,dim=c(10,4,14),dimnames=list(1:10,names_state,names_population))  
for (i in 1:14){
  qaly_m[1,,i]<-m_M[1,,i] * uti  
}                     
lifeyear<-0 
lifeyear_m<-array(0,dim=c(10,4,14),dimnames=list(1:10,names_state,names_population))  
for (i in 1:14){
  lifeyear_m[1,,i]<-m_M[1,,i]*year
}
```

```{r}
p9<-array(NA,dim=c(10,n_population),dimnames=list(1:10,names_population))
for (i in 1:14){
  if (i==7 | i==14){
    for (j in 1:10)
      p9[j,i]<-p_ccvd_acvd[i]*(1-p8[j,i])
  }
  else {
    for (j in 1:5){
      p9[j,i]<-p_ccvd_acvd[i]*(1-p8[j,i])
    }
    for (j in 6:10){
      p9[j,i]<-p_ccvd_acvd[i+1]*(1-p8[j,i])
    }
  }
}

p10<-array(NA,dim=c(10,n_population),dimnames=list(1:10,names_population))
for (i in 1:14){
  if (i==7 | i==14){
    for (j in 1:10)
      p10[j,i]<-p_live_cvd[i]
  }
  else {
    for (j in 1:5){
      p10[j,i]<-p_live_cvd[i]
    }
    for (j in 6:10){
      p10[j,i]<-p_live_cvd[i+1]
    }
  }
}

```

```{r}
for (i in 1:14){
  for (j in 1:9){
    m_M[j+1,,i] <- m_M[j,,i] %*% a_P[,,j,i]
    n_cnew[j+1,1,i] <- m_M[j,1,i] * p10[j,i]   
    n_clive[j+1,1,i]<-m_M[j,1,i]*a_P["s1","s2",j,i] +m_M[j,2,i]*p9[j,i]
    qaly_m[j+1,,i]<-m_M[j+1,,i] * uti+n_clive[j+1,1,i]*uti2 
    lifeyear_m[j+1,,i]<-m_M[j+1,,i]*year
  }
  n_cvd[i]<-sum(n_cnew[1:10,,i])
  n_cd[i]<-m_M[10,4,i]
  n_nd[i]<- m_M[10,3,i]
  n_d[i]<-n_cd[i]+n_nd[i]
  qaly[i]<-sum(qaly_m[1:10,,i])
  lifeyear[i]<-sum(lifeyear_m[1:10,,i])
}
m_M[, , 1]

```

```{r results='asis'}
print(xtable(data.frame(n_cvd,row.names = names_population)))
```

```{r results='asis'}
N_cvd <- sum(n_cvd)
N_cd <- sum(n_cd)
N_nd <- sum(n_nd)
N_d <- sum(n_d)
QALY <- sum(qaly)
LIFEYEAR <- sum(lifeyear)
print(xtable(data.frame(N_cvd,N_cd,N_nd,N_d, QALY, LIFEYEAR),
      caption = "Distribution of the population"),
      caption.placement="top",comment=FALSE)
```

